/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cotehakemate;


/**
 *
 * @author SEBCOM
 */
public class frm_nuevo_torneo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_nuevo_torneo
     */
    public frm_nuevo_torneo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombre_organizador_torneo = new javax.swing.JLabel();
        lbl_nombre_torneo = new javax.swing.JLabel();
        lbl_edicion_torneo = new javax.swing.JLabel();
        txt_organizador = new javax.swing.JTextField();
        txt_nombre_torneo = new javax.swing.JTextField();
        txt_edicion_torneo = new javax.swing.JTextField();
        btn_guardar_torneo = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lbl_nombre_organizador_torneo.setText("ORGANIZADOR:");

        lbl_nombre_torneo.setText("NOMBRE DEL TORNEO:");

        lbl_edicion_torneo.setText("EDICION:");

        btn_guardar_torneo.setText("GUARDAR");

        btn_siguiente.setText("SIGUIENTE");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_guardar_torneo)
                    .addComponent(lbl_edicion_torneo)
                    .addComponent(lbl_nombre_torneo)
                    .addComponent(lbl_nombre_organizador_torneo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_nombre_torneo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_organizador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_edicion_torneo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btn_siguiente)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre_organizador_torneo)
                    .addComponent(txt_organizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre_torneo)
                    .addComponent(txt_nombre_torneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_edicion_torneo)
                    .addComponent(txt_edicion_torneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar_torneo)
                    .addComponent(btn_siguiente))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        frm_cotejar obj=new frm_cotejar();
        MDI_MENU.desktopPane.add(obj);
       obj.toFront();
       obj.setVisible(true);
    }//GEN-LAST:event_btn_siguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar_torneo;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JLabel lbl_edicion_torneo;
    private javax.swing.JLabel lbl_nombre_organizador_torneo;
    private javax.swing.JLabel lbl_nombre_torneo;
    private javax.swing.JTextField txt_edicion_torneo;
    private javax.swing.JTextField txt_nombre_torneo;
    private javax.swing.JTextField txt_organizador;
    // End of variables declaration//GEN-END:variables
}
