/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cotehakemate;

import static cotehakemate.MDI_MENU.desktopPane;
import static cotehakemate.frm_cotejar.t1;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEBCOM
 */
public class frm_verRegistro extends javax.swing.JInternalFrame {

    public static DefaultTableModel modelo2;

    /**
     * Creates new form frm_verRegistro
     */

    public frm_verRegistro() {
        initComponents();
        Preparar();
    }

    public void Preparar() {
        modelo2 = new DefaultTableModel();
        modelo2.addColumn("Anillo");
        modelo2.addColumn("Nombre");

        modelo2.addColumn("Tipo");
        modelo2.addColumn("Color");
        modelo2.addColumn("Peso");

        tabla2.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        btn_borrar_registar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla2);

        btn_borrar_registar.setText("BORRAR");
        btn_borrar_registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrar_registarActionPerformed(evt);
            }
        });

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btn_borrar_registar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_borrar_registar)
                    .addComponent(jButton1))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrar_registarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrar_registarActionPerformed
        int fila_eliminada = tabla2.getSelectedRow();
        if (fila_eliminada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione la Fila");
        } else {
            modelo2 = (DefaultTableModel) tabla2.getModel();
            modelo2.removeRow(fila_eliminada);
        }
    }//GEN-LAST:event_btn_borrar_registarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
frm_cotejar v3=new frm_cotejar();
        desktopPane.add(v3);
        v3.show(); 
        for (int i = 0; i < tabla2.getRowCount(); i++) {
            String Datos[] = new String[5];
            Datos[0] = tabla2.getValueAt(i, 0).toString();
            Datos[1] = tabla2.getValueAt(i, 1).toString();
            Datos[2] = tabla2.getValueAt(i, 2).toString();
            Datos[3] = tabla2.getValueAt(i, 3).toString();
            Datos[4] = tabla2.getValueAt(i, 4).toString();

            frm_cotejar.t1.addRow(Datos);
        }

        
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar_registar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
