/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cotehakemate;

import static cotehakemate.MDI_MENU.desktopPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author MANUEL CARRION
 */
public class frm_registro extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_registro
     */
    DefaultTableModel t;

    public frm_registro() {
        initComponents();
        PrepararTabla();

    }

    private void PrepararTabla() {
        String titulos[] = {"ANILLO", "NOMBRE", "TIPO", "COLOR", "PESO"};
        t = new DefaultTableModel(null, titulos);
        jTable1.setModel(t);
//frm_verRegistro tabla2=new frm_verRegistro();
//        tabla2.setVisible(true);        
    }

    private void limpiar() {
        txt_anillo.setText("");
        txt_color.setText("");
        txt_peso.setText("");
        txt_tipo.setText("");
        txt_nombre.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private static boolean bandera = false;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_anillo = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        lbl_color = new javax.swing.JLabel();
        lbl_peso = new javax.swing.JLabel();
        txt_anillo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        txt_peso = new javax.swing.JTextField();
        btn_guardar_registro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_guardar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lbl_anillo.setText("ANILLO:");

        lbl_nombre.setText("NOMBRE:");

        lbl_tipo.setText("TIPO:");

        lbl_color.setText("COLOR:");

        lbl_peso.setText("PESO.");

        txt_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipoActionPerformed(evt);
            }
        });

        btn_guardar_registro.setText("CARGAR");
        btn_guardar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_registroActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_anillo)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_tipo)
                    .addComponent(lbl_color)
                    .addComponent(lbl_peso))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_anillo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txt_nombre)
                            .addComponent(txt_tipo)
                            .addComponent(txt_color)
                            .addComponent(txt_peso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_guardar_registro)
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_editar)
                .addGap(83, 83, 83)
                .addComponent(btn_eliminar)
                .addGap(89, 89, 89)
                .addComponent(btn_guardar)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_anillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_anillo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbl_tipo))
                            .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbl_color))
                            .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_peso))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar_registro)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar)
                            .addComponent(btn_eliminar)
                            .addComponent(btn_editar))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipoActionPerformed

    }//GEN-LAST:event_txt_tipoActionPerformed

    private void btn_guardar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_registroActionPerformed
        try {

            if (bandera == false) {

                cls_registro obj_congelado = new cls_registro(txt_anillo.getText(), (txt_nombre.getText()), txt_tipo.getText(), txt_color.getText(), Double.parseDouble(txt_peso.getText()));
                t = (DefaultTableModel) jTable1.getModel();
                String datos[] = {obj_congelado.getAnillo(), obj_congelado.getNombre(), obj_congelado.getTipo(), obj_congelado.getColor(), String.valueOf(obj_congelado.getPeso()),};
                t.addRow(datos);
                // frm_verRegistro.modelo2.addRow(datos);

                //limpiar();
            }
            if (bandera == true) {
//              "F.Caducidad", "Lote", "F.Envasada", "Pais", "Temperatura", "Producto"
                jTable1.setValueAt(txt_anillo.getText(), jTable1.getSelectedRow(), 0);
                jTable1.setValueAt(txt_nombre.getText(), jTable1.getSelectedRow(), 1);
                jTable1.setValueAt(txt_tipo.getText(), jTable1.getSelectedRow(), 2);
                jTable1.setValueAt(txt_color.getText(), jTable1.getSelectedRow(), 3);
                jTable1.setValueAt(txt_peso.getText(), jTable1.getSelectedRow(), 4);
                limpiar();

            }
            bandera = false;
            jTable1.clearSelection();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_guardar_registroActionPerformed


    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(null, "Sus datos se han guardado satisfactoriamente");
            frm_verRegistro v3 = new frm_verRegistro();
            desktopPane.add(v3);
            v3.show();
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String Datos[] = new String[5];
                Datos[0] = jTable1.getValueAt(i, 0).toString();
                Datos[1] = jTable1.getValueAt(i, 1).toString();
                Datos[2] = jTable1.getValueAt(i, 2).toString();
                Datos[3] = jTable1.getValueAt(i, 3).toString();
                Datos[4] = jTable1.getValueAt(i, 4).toString();

                frm_verRegistro.modelo2.addRow(Datos);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR");
        }


    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        try {
            if (jTable1.getSelectedRow() >= 0) {
                //              "F.Caducidad", "Lote", "F.Envasada", "Pais", "Temperatura", "Producto"
                txt_anillo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                txt_nombre.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                txt_tipo.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                txt_color.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
                txt_peso.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());

                bandera = true;
            } else {
                JOptionPane.showMessageDialog(null, "Selecciona una fila");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int fila_eliminada = jTable1.getSelectedRow();
        if (fila_eliminada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione la Fila");
        } else {
            t = (DefaultTableModel) jTable1.getModel();
            t.removeRow(fila_eliminada);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila = jTable1.getRowCount();
        int i;
        String valores = "";
        String valores1 = "";

        for (i = 0; i < fila; i++) {
            String valor = (String) jTable1.getValueAt(i, 1);
            valores += valor;

            // Con esta condición solo ponemos comas hasta el penúltimo valor :)
            if (i < (fila - 1)) {
                valores += ", ";
            }
        } for (i = 0; i < fila; i++) {
            String valor1 = (String) jTable1.getValueAt(i, 1);
            valores1 += valor1;
        
//         for (int j = 0; j < fila; j++) {
//            String valor = (String) jTable1.getValueAt(i, 1);
//                 if (valores==valor) {
//                     boolean mismonombre=true;
//                     System.out.println(mismonombre);
//                 }
//           }
        try {

            String[] datos1 = valores.split(",");
            List<String> emparejados = new ArrayList<String>();
            Random rand = new Random();
            int randomNum = rand.nextInt(((datos1.length - 1) - 0) + 1);
            int equiposExtraidos = 0;
            String aux1 = "";
            String aux2 = "";
//        for (int j = 0; j < fila; j++) {
//            String valor = (String) jTable1.getValueAt(i, 1);
//                 if (valores==valor) {
//                     boolean mismonombre=true;
//                     System.out.println(mismonombre);
//                 }
//           }

            while (equiposExtraidos < datos1.length) {

//            if (valores == jTable1.getValueAt(i, 1)) {
//                break;
//            }
//            if (txt_peso!=(txt_peso)) {
//                break;
//            }
                if (emparejados.size() == datos1.length - 1) {
                    break;
                }
                String equipo1 = "";
                do {
                    randomNum = rand.nextInt(((datos1.length - 1) - 0) + 1);
                    equipo1 = datos1[randomNum];
                } while (emparejados.contains(datos1[randomNum]));
                emparejados.add(equipo1);
                String equipo2 = "";
                do {

                    randomNum = rand.nextInt(((datos1.length - 1) - 0) + 1);
                    equipo2 = datos1[randomNum];
                } while (emparejados.contains(datos1[randomNum]));
                {
                    if (valores != valores1) {

                        emparejados.add(equipo2);
                        aux1 = equipo1;
                        aux2 = equipo2;
                        //System.out.println(equipo1 + " vs " + equipo2);
                        //cotejos.append(aux1 + " vs " + aux2 + "\n");
                        equiposExtraidos++;
                        t = (DefaultTableModel) jTable1.getModel();
                        String data[] = {aux1, "vs", aux2};
                        t.addRow(data);
                    }
                }
            }
            for (String equipo : datos1) {
                if (!emparejados.contains(equipo)) {
                    String data3[] = {"- Exento: ", equipo};
                    t.addRow(data3);

                }
            }

        } catch (Exception e) {
        }

        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_guardar_registro;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_anillo;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_peso;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JTextField txt_anillo;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
